# Generated by Django 5.0.7 on 2024-07-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_city_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='number_of_searches',
            field=models.IntegerField(default=0),
        ),
    ]
